### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Burnleydev1**
Fixes #41
This is an RFC, as it needs some enhancements and corrections before being merged.

### CODE REVIEW

**Comment by Burnleydev1** [comment]
This PR addresses https://github.com/istudybucket/istudybucket-backend/issues/41

**Review by elroykanye — COMMENTED** [review]
This looks good. I think we can borrow some ideas from this [template](https://gist.github.com/PurpleBooth/b24679402957c63ec426) too.

**Comment by Burnleydev1** [comment]
> Check my edit on your first comment for this PR. I think we should create a PR template like this so it links the PR to an issue.

Great Idea, I will work on that asap :)

**Comment by Burnleydev1** [comment]
> This looks good. I think we can borrow some ideas from this [template](https://gist.github.com/PurpleBooth/b24679402957c63ec426) too.

I did some changes based on this

**Review by elroykanye — APPROVED** [review]
Looks good. We will have to update the project to match some aspects of these guidelines. 
I hope we are able to complete by August 😅

**Comment by Burnleydev1** [comment]
I hope so too :)

**Pull request merged**
